### ISSUE TITLE
Unable to run perftest with TCP

### ISSUE THREAD

**Issue by hsienyan** [rticommunity/rtiperftest#137]
I tried to run pertest on localhost with TCP. 
I run the publisher with 
./bin/x64Linux3gcc5.4.0/release/perftest_cpp -pub -transport TCP 

and subscriber with 
./bin/x64Linux3gcc5.4.0/release/perftest_cpp -sub -transport TCP

but it prompted out below error:

/**********************ERROR************************************/

RTI Perftest 2.3.2 (RTI Connext DDS 5.3.0)
NDDS_Transport_TCPv4_new:internal error: bind server socket
[D0001|ENABLE]DDS_DomainParticipantConfigurator_setup_custom_transports:!create custom transport plugin

[D0001|ENABLE]DDS_DomainParticipantConfigurator_enable:!install transport plugin aliases = custom transports

[D0001|ENABLE]DDS_DomainParticipant_enableI:!enable transport configurator

DDSDomainParticipant_impl::createI:ERROR: Failed to auto-enable entity

DomainParticipantFactory_impl::create_participant():!create failure creating participant

Problem creating participant.
Test ended.

/**********************ERROR************************************/

I realized it is the port issue.
How could I solve this?

Thank you.

**Comment by javmorcas** [comment]
Hi @hsienyan, thanks for your feedback. I see you closed this issue already, but just to clarify:

As you mentioned, the issue is because you are trying to use twice the same port in the same machine. By default, when using TCPv4 and if you don't specify the port (as a command line option), it will try to use 7400. The first application will be able to get it, but the second will not.

So, if you are using RTI Perftest for the publisher and subscriber application with TCPv4, you should add a different port for one of the app.

Let me know if that makes sense to you and if you need some more help there.

**Comment by hsienyan** [comment]
@javmorcas  Thank for your help. I managed to run it.
