### ISSUE TITLE
Async pub shouldn't be necessary with data >63k as long as best effort is used

### ISSUE THREAD

**Issue by rgrti** [rticommunity/rtiperftest#297]
Perftest docs section 5.1 state:

> If <bytes> is bigger than 63000, RTI Perftest will enable the use of Asynchronous Publishing and Unbounded Sequences.

But 6.4.1 of the user manual says:

> For example, to send data larger than 63K reliably using UDP/IP, you must configure Connext DDS to send the data using asynchronous_Publishers_.

6.5.20 says something similar:

> For instance, for sending large data reliably, an asynchronous thread must be used

I can't find anything that specifically says you can use synchronous mode with best-effort with large data, but everything I read about async pub says it is only required to "reliably" send data over 63k.

Can perftest be changed to allow synchronous transfers or larger data when using best effort?

**Comment by javmorcas** [comment]
@rgrti, the behavior you ask for completely correct: Sending *Large Data* in `Best Effort` can be done *synchronously* or *Asynchronously*. Sending *Large Data* in `Reliable` reliability requires the use of *Asynchronous publishing*.

**RTI Perftest**'s Current behavior is not to distinguish between `Reliable` and `Best Effort` in order to switch to *Asynchronous Publishing*, when using *Large Data*. I will discuss this behavior in the next Performance meeting and check if we want to add this capability.

That being said: The general recommendation is that for Large Data we should use Asynchronous Publishing, since it adds the capability of using a flow controller (which is nice) and it uses another thread to avoid blocking the main thread (the one that does the `write()`). It is also a recommendation to use `Reliable` reliability when sending really large samples.
