### ISSUE TITLE
Larger datalen values will prevent stats from being printed at the end of a test

### ISSUE THREAD

**Issue by rgrti** [rticommunity/rtiperftest#298]
I'm playing around with sending some larger data over perftest, but the output I'm getting doesn't make sense to me. As I increase the datalen, latency stats are printed only on the subscriber side, and eventually not at all. 

All use default xml

### Test 1
Pub side: C:\Users\user\Documents\rti_workspace\rti_perftest-3.0.1_x64Win64VS2010>bin\x64Win64VS2010\release\perftest_cpp.exe -pub -bestEffort -transport UDPv4 -allowInterfaces 127.0.0.1 -latencyCount 1 -sleep 30000 -writerStats -numIter 1 -dataLen 12345678

Sub side: C:\Users\user\Documents\rti_workspace\rti_perftest-3.0.1_x64Win64VS2010>bin\x64Win64VS2010\release\perftest_cpp.exe -sub -bestEffort -transport UDPv4 -allowInterfaces 127.0.0.1 -dataLen 12345678

 
Pub side output (no issues):

> Waiting to discover 1 subscribers ...
> Waiting for subscribers announcement ...
> Sending 50 initialization pings ...
> Publishing data ...
> Pulled samples: 0
> 
> ********** New data length is 12345678
> Length: 12345678 Latency: Ave 24243 us Std 0.0 us Min 24243 us Max 24243 us 50% 24243 us 90% 24243 us 99% 24243 us 99.99% 24243 us 99.9999% 24243 us
> Serialization/Deserialization: 1871.897 us / 1666.780 us / TOTAL: 3538.677 us
> Pulled samples: 0
> Finishing test...
> Test ended.

Sub side output (no issues):

> Waiting to discover 1 publishers ...
> Waiting for data...
> 
> ********** New data length is 12345678
> Length: 12345678 Packets: 1 Packets/s(ave): 151 Mbps(ave): 14996.3 Lost: 0 (0.00%)
> Finishing test...
> Test ended.

### Test 2
Same command, change datalen to 22345678

pub side output: 

> Waiting to discover 1 subscribers ...
> Waiting for subscribers announcement ...
> Sending 50 initialization pings ...
> Publishing data ...
> Pulled samples: 0
> Pulled samples: 0
> Finishing test...
> Test ended.

sub side output:

> Waiting to discover 1 publishers ...
> aiting for data...
> ********** New data length is 22345678
> Length: 22345678 Packets: 1 Packets/s(ave): 101 Mbps(ave): 18062.6 Lost: 0 (0.00%)
> Finishing test...
> Test ended.

Notice the pub side doesn't include latency information (sometimes it does, sometimes it doesnt)

### Test 3
Same command, change datalen to 33345678
pub side output:

> Waiting to discover 1 subscribers ...
> Waiting for subscribers announcement ...
> Sending 50 initialization pings ...
> Publishing data ...
> Pulled samples: 0
> Pulled samples: 0
> Finishing test...
> Test ended.

sub side output: 

> Waiting to discover 1 subscribers ...
> Waiting for subscribers announcement ...
> Sending 50 initialization pings ...
> Publishing data ...
> Pulled samples: 0
> Pulled samples: 0
> Finishing test...
> Test ended.

Neither the pub or sub side prints latency info. "pulled samples: 0" is printed twice like in test 2

**Comment by javmorcas** [comment]
Hi @rgrti 

I've been able to reproduce your issues. Some of them can be explained due to the fact that you are using Best Effort.

In my case I do see issues even with `12345678 Bytes` (my laptop is older than yours most likely):

**Pub**
```
$ bin/x64Darwin17clang9.0/release/perftest_cpp -pub -transport UDPv4 -allowInterfaces 127.0.0.1 -latencyCount 1 -sleep 30000 -numIter 1 -dataLen 12345678 -best
[...]
Waiting to discover 1 subscribers ...
Waiting for subscribers announcement ...
Sending 50 initialization pings ...
Publishing data ...
Finishing test...
Test ended.
```

**Sub**
```
$ bin/x64Darwin17clang9.0/release/perftest_cpp -sub -transport UDPv4 -allowInterfaces 127.0.0.1 -dataLen 12345678 -best
[...]
Waiting to discover 1 publishers ...
Waiting for data...
Finishing test...
Test ended.
```

This is the same you see in **Test 3**. Now, I am pretty sure that this is due to the use of `Best Effort` reliability. I believe the problem might be related to the fact that we are doing fragmentation at the DDS level (63kB), but also at IP level (1500B), causing that the probability of a single fragment being lost is high (a single fragment being lost means that the whole sample is lost). I tried to solve this by using a flow controller at the DDS level, to slow down a bit the sending of the data (`-flow 1Gbps`), and it seems to help. (AI: Could you try and see if it works for you?).

The other way to solve this, is if I use `RELIABLE` reliability. In this case I always get the output in the subscriber side, but sometimes in the publisher side I don't see the latency information. **This might be indeed an issue in the product design**. The explanation being the following: 

- The system sends the first sample, which happens to be the last sample and a *latency sample* (a sample that needs to be answered by the subscriber).
- The sending process begins (an asynchronous thread is going to start the process of writing all the fragments).
- Right after a sample is sent to all subscribers (in this case 1) saying "hey, we are finishing". This uses the `Throughput` topic as well, and the same asynchronous thread.
- The subscriber receives both samples in order.
- The first one is a latency sample so it triggers sending it back through the `Latency` Topic, with another writer, asynchronous as well.
- The subscriber also reacts to the second sample, but it will use a different writer and topic, the `Announcement` topic to signal with a sample: "Ok, I received your Finishing signal, I'll wrap up and finish".
- It can happen that the sample signaling that the subscriber moved to the finishing state reaches the subscriber before the latency sample, because it is a small sample and it uses a different topic. In that case the publisher will not wait and will start deleting listeners, readers, writers and all the DDS entities, which will lead to miss the latency sample.

This is an interesting behavior that was not expected, as in general we always send way more samples than one, so if the latency sample is lost, this will not happen. I will investigate this further.

As described above, we have not tested this tool sending one single sample. In general I would suggest sending a significative number of samples, mainly because the statistic information that you will get will be more significative: Individual samples' latency might be affected by OS events (such as other processes interfering or changes of context), also, the changes of samples being lost might be significative. In general I like doing at least 50 or 30 samples. In fact, our tests usually last for 2 or 3 minutes. That being said, I understand you might want to test something specific, in that case, dismiss this suggestion :).

**Comment by rgrti** [comment]
Thanks for the detailed response, I was able to see the results when switching to reliable (I guess I figured my loopback interface wouldn't drop traffic). 

I also increased my numiter to avoid the sequence you describe, it does seem to work. But I'm wondering if there are special cases where regardless of the number of samples you send, if a throughput and announcement comes through to the subscriber at the same time, will this cause the same issue?

I'm also seeing a new issue when increasing my datalen and numiter, my publisher seems to hang right before the "finishing test..." line, my subscriber has already completed and gracefully exited minutes beforehand. 

### Pub side example:
`PS C:\Users\ross\Documents\rti_workspace\rti_perftest-3.0.1_x64Win64VS2010> Measure-Command {.\bin\x64Win64VS2010\release\perftest_cpp.exe -pub -transport UDPv4 -allowInterfaces 127.0.0.1 -latencyCount 1 -sleep 30000 -writerStats -numIter 3 -dataLen 1234567890 | Out-Default}`

### Pub side output:
```
Waiting to discover 1 subscribers ...
Waiting for subscribers announcement ...
Sending 50 initialization pings ...
Publishing data ...
Pulled samples:       0
Pulled samples:       0
Pulled samples:       0

********** New data length is 1234567890
One way Latency: 11879059 us  Ave 10330428 us  Std 1548631.5 us  Min 8781796 us  Max 11879059
Length: 1234567890  Latency: Ave 10330428 us  Std 1548631.5 us  Min 8781796 us  Max 11879059 us  50% 11879059 us  90% 11879059 us 99% 11879059 us  99.99% 11879059 us  99.9999% 11879059 us 
<<<RG: Hangs after printing the above line>>>
Finishing test...
Test ended.
One way Latency: 15107255 us  Ave 11922703 us  Std 2582542.2 us  Min 8781796 us  Max 15107255
Serialization/Deserialization: 185043.873 us / 180538.663 us / TOTAL: 365582.536 us
Pulled samples:       2


Days              : 0
Hours             : 0
Minutes           : 6
Seconds           : 57
Milliseconds      : 567
Ticks             : 4175676168
TotalDays         : 0.00483295852777778
TotalHours        : 0.115991004666667
TotalMinutes      : 6.95946028
TotalSeconds      : 417.5676168
TotalMilliseconds : 417567.6168
```
### Sub side example:
`PS C:\Users\ross\Documents\rti_workspace\rti_perftest-3.0.1_x64Win64VS2010> Measure-Command {.\bin\x64Win64VS2010\release\perftest_cpp.exe -sub -transport UDPv4 -allowInterfaces 127.0.0.1 -dataLen 1234567890 | Out-Default}`

Sub side output:
Waiting to discover 1 publishers ...
Waiting for data...


********** New data length is 1234567890
```
Packets:        1  Packets/s:       0  Packets/s(ave):       0  Mbps:     0.0  Mbps(ave):     0.0  Lost:     0 (0.00%)
Packets:        1  Packets/s:       0  Packets/s(ave):       0  Mbps:     0.0  Mbps(ave):     0.0  Lost:     0 (0.00%)
Packets:        1  Packets/s:       0  Packets/s(ave):       0  Mbps:     0.0  Mbps(ave):     0.0  Lost:     0 (0.00%)
Packets:        1  Packets/s:       0  Packets/s(ave):       0  Mbps:     0.0  Mbps(ave):     0.0  Lost:     0 (0.00%)
Packets:        1  Packets/s:       0  Packets/s(ave):       0  Mbps:     0.0  Mbps(ave):     0.0  Lost:     0 (0.00%)
Packets:        1  Packets/s:       0  Packets/s(ave):       0  Mbps:     0.0  Mbps(ave):     0.0  Lost:     0 (0.00%)
Packets:        1  Packets/s:       0  Packets/s(ave):       0  Mbps:     0.0  Mbps(ave):     0.0  Lost:     0 (0.00%)
Packets:        1  Packets/s:       0  Packets/s(ave):       0  Mbps:     0.0  Mbps(ave):     0.0  Lost:     0 (0.00%)
Packets:        1  Packets/s:       0  Packets/s(ave):       0  Mbps:     0.0  Mbps(ave):     0.0  Lost:     0 (0.00%)
Packets:        1  Packets/s:       0  Packets/s(ave):       0  Mbps:     0.0  Mbps(ave):     0.0  Lost:     0 (0.00%)
Packets:        1  Packets/s:       0  Packets/s(ave):       0  Mbps:     0.0  Mbps(ave):     0.0  Lost:     0 (0.00%)
Packets:        2  Packets/s:       0  Packets/s(ave):       0  Mbps:  9866.8  Mbps(ave):   822.2  Lost:     0 (0.00%)
Packets:        2  Packets/s:       0  Packets/s(ave):       0  Mbps:     0.0  Mbps(ave):   759.0  Lost:     0 (0.00%)
Packets:        2  Packets/s:       0  Packets/s(ave):       0  Mbps:     0.0  Mbps(ave):   704.8  Lost:     0 (0.00%)
Packets:        2  Packets/s:       0  Packets/s(ave):       0  Mbps:     0.0  Mbps(ave):   657.8  Lost:     0 (0.00%)
Packets:        2  Packets/s:       0  Packets/s(ave):       0  Mbps:     0.0  Mbps(ave):   616.7  Lost:     0 (0.00%)
Packets:        2  Packets/s:       0  Packets/s(ave):       0  Mbps:     0.0  Mbps(ave):   580.4  Lost:     0 (0.00%)
Packets:        2  Packets/s:       0  Packets/s(ave):       0  Mbps:     0.0  Mbps(ave):   548.2  Lost:     0 (0.00%)
Packets:        2  Packets/s:       0  Packets/s(ave):       0  Mbps:     0.0  Mbps(ave):   519.3  Lost:     0 (0.00%)
Packets:        2  Packets/s:       0  Packets/s(ave):       0  Mbps:     0.0  Mbps(ave):   493.3  Lost:     0 (0.00%)
Packets:        2  Packets/s:       0  Packets/s(ave):       0  Mbps:     0.0  Mbps(ave):   469.8  Lost:     0 (0.00%)
Packets:        2  Packets/s:       0  Packets/s(ave):       0  Mbps:     0.0  Mbps(ave):   448.5  Lost:     0 (0.00%)
Length: 1234567890  Packets:        3  Packets/s(ave):       0  Mbps(ave):  1285.0  Lost:     0 (0.00%)
Finishing test...
Test ended.

Days              : 0
Hours             : 0
Minutes           : 0
Seconds           : 52
Milliseconds      : 901
Ticks             : 529016724
TotalDays         : 0.000612287875
TotalHours        : 0.014694909
TotalMinutes      : 0.88169454
TotalSeconds      : 52.9016724
TotalMilliseconds : 52901.6724
```

As you can see the subscriber took 52 seconds and exited, while the publisher stuck around for almost 7 minutes

**Comment by rgrti** [comment]
Something else I'm seeing, when I use the pub/sub commands in my above comment, and add `-flowController 1Gbps` to the publisher side, the publisher (and therefore the subscriber) hangs at:
`Publishing data...`
and `Waiting for data...`

**Comment by javmorcas** [comment]
First, thanks @rgrti for your answer.

Now, I was unable to reproduce this last behavior you mentioned. Would you be able to run and debug this issue and see where this is hanging?

I am concern it might be related to the fact that you are using Windows for these tests (where we have seen issues with fragmentation in the past -- See some kb articles about this in the community portal). I wonder if that is the reason why I don't see the issue.

**Independently**, and just for the sake of getting the right results: What are you trying to test with this test? In general I would not recommend the use `-latencyCount 1` in this case, since you are in a **Throughput Test** (If you were doing a latency Test `latencyCount = 1` by default).

The behavior you will see in this case is:

- You send 3 samples, 1,2,3 one after the other (since you are using asynchronous in a throughput test, there is no blocking since the send queue is 50 by default).
- the Asynchronous Thread fragments them and then tries to send them one after the other.
- At the IP level you get even more fragmentation due to the MTU size being 1500 or 9000
- That is likely to cause a lot of fragments being lost and on Windows a lot of fragments waiting to be reassembled (that lasts for a long time). 
- At the same time, you are trying to answer them as soon as the packets are received (the 3 of them). That is going to use the same network as your publisher, therefore publisher and subscriber apps will compete for the same BW resources, hogging even more the system.

Depending on what you want to test, I would recommend:
- sendqueue = 1
- flowController 1Gbps or 10Gbps
- If this is a throughput test, numIters = X (20, 30...) and latencyCount = X/10 (one out of every 10, for example, even less often if possible). You cannot test latency and throughput here at the same time.
- If this is a latency test, -latencyTest and -numIter = 20/30.
- If this a different kind of test, let me know what do you seek and I will try to find the right test for you using RTI Perftest.

In any case: That does not prevent the test to finish though, so, it means that the samples are received in the end (after who knows how many tries). Therefore the test should end, but it doesn't... I wonder then if the system is sending/receiving samples at that point, or waiting for some fragmentation at the IP level to expire (not sure). If we could find the place where the publisher/subscribers are stopped, that would be helpful.

**Comment by javmorcas** [comment]
Wrt `-flowController`, this applies to both pub and sub sides, since the subscriber has to send back samples, and those will use a writer, if the writer is using large data you will need asynchronous, and if you are using asynchronous you might want to use a flow Controller.

**Comment by javmorcas** [comment]
Notes from performance meeting: Notify in the publisher side that no samples were received. Also in the subscriber side.

**Comment by javmorcas** [comment]
For FlatData (Large Data Sizes) -- Print resource limits, as they are calculated dynamically.

**Comment by javmorcas** [comment]
See #302 and #303 For the 2 issues described there.
