### ISSUE TITLE
Incorrect readme example referencing 1-to-2, Multicast, Reliable, UDPv4

### ISSUE THREAD

**Issue by zergler** [rticommunity/rtiperftest#31]
In this [README](https://github.com/rticommunity/rtiperftest/blob/master/srcDoc/examples.rst#1-to-2-multicast-reliable-udpv4) the 1-to-2, Multicast, Reliable, UDPv4 example should have subscribers with the command line arguments -sidMultiSubTest 0 and -sidMultiSubTest 1 for each subscriber that is launched.

**Comment by javmorcas** [comment]
I completely agree with your comment. Not only that, but I am going to take the oportunity and remove 2 command-line parameters not needed for this concrete test: `-dataLen 200 -batchSize 6400`. Therefore the commands would be: 

## 1-to-2, Multicast, Reliable, UDPv4

-  Publisher:
```
bin/<arch>/release/perftest_cpp -pub -noPrint -pidMultiPubTest 0 -sendQueueSize 32 -numSubscribers 2 -latencyCount 1000 -dataLen 200 -multicast -executionTime 100
```
-  Subscriber 1:
```
bin/<arch>/release/perftest_cpp -sub -noPrint -multicast -sidMultiSubTest 0
```
-  Subscriber 2:
```
bin/<arch>/release/perftest_cpp -sub -noPrint -multicast -sidMultiSubTest 1
```

This will be fixed in the `master` branch and it will be also part of the `2.3` Release.

**Comment by javmorcas** [comment]
The issue should be fixed by now.
