### ISSUE TITLE
Help with Routing Service

### ISSUE THREAD

**Issue by vsaguero** [rticommunity/rtiperftest#32]
Hi all,

I am trying to test the following scenario:

One publisher located in subnet A and two publishers in subnet B (A and B are obviously connected via standard router). Can anyone help me, or at least give me some hints, in order to use Routing Service to communicate publisher with subscribers?

Maybe I am lost, so any tip or advice (redirect me to some documentation) should be ok :)

Thanks in advance

**Comment by javmorcas** [comment]
Hi Víctor,

Let me see if I understood your scenario:

- You have network A, there you have a computer with an RTI Perftest publisher application
- You have network B, and there you have another computer (or computers) with 2 instances of RTI Perftest acting as subscribers.
- Network A and B are separated by a standard router (like, layer 3 router, not routing service).

Is this correct? Let me know if I missed something.

In this scenario you don't really need to use RTI Routing Service. I believe what the RTI Perftest applications are trying to discover themselves via multicast, however, most routers don't allow multicast packets across networks.

My initial approach would be using the `-peer` parameter to explicitly specify where are the applications you want to communicate to. The parameters for the applications would be something like:

**Publisher 1 (Network A, Machine with IP_machine1):**
```
perftest_cpp -pub -numSubscribers 2 -peer <IP_machine2> -peer <IP_machine3> <rest of parameters>
```

**Subscriber 1 (Network B, Machine with IP_machine2):**
```
perftest_cpp -sub -sidMultiSubTest 0 -peer <IP_machine1> <rest of parameters>
```

**Subscriber 2 (Network B, Machine with IP_machine3):**
```
perftest_cpp -sub -sidMultiSubTest 1 -peer <IP_machine1> <rest of parameters>
```

Let me know if this helps.

Regards,
Javier

**Comment by vsaguero** [comment]
Hello Javi,

Thanks for the quick reply.

You understand my scenario. As you told me I have used `-peer` parameter and the unicast test is working properly. Now I can start doing some tests in order to quantify RTI-DDS QoS advantages.

By the way, standard multicast test is working in my scenario (Machine A sends packet to the multicast group and, when the router is receiving one IGMP from Machine B or C it starts forwarding packets). However it doesn't work with RTIperf. I think in this case, Machine B IGMP should reach Machine A since the publisher is waiting to discover at least one publisher. This is the reason why I am asking about the routing service.

Thank so much for the help.

**Comment by javmorcas** [comment]
Glad to hear that you got the unicast scenario properly working.

I believe you should investigate further why you are not achieving multicast discovery between your DDS applications: If the router is forwarding the IGMP packages, I would expect that the DDS multicast packages should be received as well.

In order to continue debugging, I would take RTI Perftest away from the equation, and try to reproduce your issue with a even simpler application: A Hello-World publisher/subscriber application (the ones generated with rtiddsgen would be great. 

Also, I think this issue should be handled via RTI Support (support@rti.com) if you have, or via our [official forums |https://community.rti.com].

As a side note: Routing Service should not be needed in these scenarios, think of routing service as a bridge between domains, with options to filter topics and do transformations (and many other options). It is not involved in the actual routing at the ip level, so it does not resolve anything for you here.

Let me know if that makes sense to you.

**Comment by vsaguero** [comment]
Let's continue debugging. Thank for your recommendations
