### ISSUE TITLE
custom.idl file not documented

### ISSUE THREAD

**Issue by howard-rti** [rticommunity/rtiperftest#327]
I modified the custom.idl file to have the definition of my custom structure.  However, this is not allowed since this file is automatically deleted and regenerated by the build.

We should document that this file should not be used by the customer to define their custom types and that any IDL files that they create should have a different file name than "custom.idl".

**Comment by javmorcas** [comment]
Hi @howard-rti, just to clarify your issue, is the problem that you named the file `custom.idl`, right? In that case we can certainly add a check prior to start the process, and add to the documentation that we do not allow the use of that name.

=== 

The only other scenario I can think of where this can happen is if:

- You generated a custom idl file and added it to the `${perftest_folder}/srcIdl/CustomType/` folder.

```
srcIdl
├── customType
│   └── test.idl
├── perftest.idl
├── perftest_ZeroCopy.idl
```

- You used the `build` script to generate the files. That process triggered the creation of the following files:

```
srcIdl
├── custom.idl (1)
├── customType
│   ├── custom.idl (2)
│   └── test.idl
├── perftest.idl
├── perftest_ZeroCopy.idl
└── test.idl
```

And then you modified `(1)` and `(2)`, but I don't think that is your scenario.

Even though, In this case I will try to delete the generated idl files right after the code is generated with them.

Thanks for your feedback.

**Comment by howard-rti** [comment]
Actually, I did modify an existing "custom.idl" file in the "customType" directory.

I saw that the "custom.idl" file had included another idl, but since I didn't know any better, I thought, why create another file, why not directly just modify the "custom.idl" file.  Fundamentally, how the build works with respect to custom types isn't well documented with regards to what files are automatically generated and should not be edited versus IDL files that user can use to add their structure that they want to test.

The perftest documentation just says this 

- Copy your IDL files into ~/rtiperftest/srcIdl/custom/
- Implement the API custom type functions of customtype.cxx

1) it probably should say something about don't name your IDL file "custom.idl".  And mention, a file with that name will be autogenerated and should not be modified

2) It should say that the file "customtype.cxx" (which is actually spelled as "CustomType.cxx", note capitalizations) is in srcCpp/CustomType.cxx.

3) I think that the use of custom types is only supported in traditional C++?  Not C, not modern C++ and not in Java right?  If so, should document restrictions.

**Comment by javmorcas** [comment]
@howard-rti, I will make that information that explicit, however, just to clarify:

There is no `custom.idl` in `${rtiperftest}/srcIdl/custom`, in fact there is not even a `custom` folder there, This means that to reach that situation you (or a given customer) would have to 

- Create explicitly a `custom` folder and then create your custom idl with whatever name you choose -- This is the process so far, and here there is one thing to fix: the name should not be "custom.idl" but that was not your issue
- Generate the code, explicitly pointing with the `--customType` command line option to the structure in your custom idl file. This would trigger the creation of the file in `${rtiperftest}/srcIdl/custom`
- Modify the file `${rtiperftest}/srcIdl/custom/custom.idl`
- Modify the `build` `--customType` command line as well to point to the new structure.

What I mean with this is that it is likely that this issue happens when you use a perftest version that you used in the past that is not clean. This does not mean that we will not fix it. We will.

**Comment by howard-rti** [comment]
Uh, maybe this is a bug with the documentation.  I copied this instruction from the documentation:
**- Copy your IDL files into ~/rtiperftest/srcIdl/custom/**

So the docs say to use a directory called "custom".  But when I tried it, it didn't work....and looking into the build.bat, I saw that it expected the user's IDL file to be in the directory "srcIdl/customType".

This is another documentation bug.

**Comment by javmorcas** [comment]
No, indeed you need the custom folder, we provide some examples in the documentation.

**Comment by howard-rti** [comment]
Yes, however, the name of the custom folder in the documentation is "srcIdl/custom", but that is wrong, the folder name needs to be "srcIdl/customType" for build scripts to work.

**Comment by javmorcas** [comment]
@howard-rti, I decided that I will rewrite the documentation for Custom Types as a top level document and not only an example and add your feedback. Please contact the performance team when you find these issues so we can quickly assist you.
