### ISSUE TITLE
Max samples for Micro results in huge memory allocation

### ISSUE THREAD

**Issue by grahonan** [rticommunity/rtiperftest#340]
https://github.com/rticommunity/rtiperftest/blob/fd1c588caf4abbe2dcafdbb84022f35b17986efa/srcCpp/RTIDDSImpl.cxx#L3496

I recommend greatly reducing this, e.g. by an order of magnitude from 5000 to 500. My Ubuntu OOM reaper killed the Perftest subscriber due to the default of 5000.

**Comment by javmorcas** [comment]
@grahonan, thanks a lot for mentioning this. I've been investigating, since the issue wasn't related to changes in the qos values for max_samples and realized that we modified:

```
const long MAX_BOUNDED_SEQ_SIZE = 1048576; // 1MB
```

Before it was 63000. This had a huge impact. For the time being my proposal is to have it as: 

```
const long MAX_BOUNDED_SEQ_SIZE = 65536;
```

I tested it in my machine and worked just fine.

**Comment by grahonan** [comment]
Hi @javmorcas, I want to reopen this issue because it recently came up in a Support escalation (see the story [here](https://docs.google.com/document/d/1_2_AKdtY30MWH3QON0mGDWbVJ4lkH_9qDOCw2KXbkyg/edit#heading=h.kbu9a35088nq)). Sergio filed issue [363](https://github.com/rticommunity/rtiperftest/issues/363) as a result, but I think this issue (340) is also very relevant. Today I had another customer trying to run Perftest with Micro 3.0.3 and the application was killed by the kernel due to being out of memory.
