### ISSUE TITLE
Modern C++ impl is not sending actual data

### ISSUE THREAD

**Issue by howard-rti** [rticommunity/rtiperftest#360]
**Description**

Because line 651 is commented out of the file https://github.com/rticommunity/rtiperftest/blob/master/srcCpp03/RTIDDSImpl.cxx

        //data.bin_data(message.data);

when using the Modern C++ API, the test doesn't actually send the data passed by the test framework but instead sends an empty buffer of the same size.  This makes the test results faster by omitting a copy of the data that's currently required when using the Modern C++.   The traditional C++ and C implementation can take advantage of a loan_contiguous() method that allows the middleware to directly use a buffer provided to the API without a copy.  But currently, that's not supported in Modern C++.  

However, Perftest should be a fair and accurate measure of performance across middlewares and across APIs of middlewares.  The test is supposed to measure the performance of a middleware transferring data created above the middleware.  For the Modern C++ API, this is not happening in the current implementation.

**How to Reproduce**

**Expected behavior**

**TODO**:
- [ ] Support for C++ Traditional
- [ ] First CR [Code Review]()
- [ ] Support for C++ Modern
- [ ] Support for Java
- [ ] Support for CS
- [ ] Automatic install testing
- [ ] Documentation
- [ ] Full [Code Review]()
- [ ] Final Merge into master

**Comment by javmorcas** [comment]
@howard-rti, this issue is under discussion, since the resolution you propose would be testing the Perftest implementation (wrapper) + the middleware's performance, which would be unfair as well.

I am afraid this will need more changes than just modifying that like of code (and the equivalent line in the opposite direction, as this is just packing the message but you need to do the same unpacking it). We might need to take the chance to unify the Traditional and Modern C++ implementations under the same infrastructure.

I will close this issue, but we will keep track of it internally (JIRA).
